@cedula=11234224
@cedula2=2354659
### Hola Mundo
GET http://localhost:5000/

### Saludo
GET http://localhost:5000/saludo/jaime?titulo=Sr

### Listar todos los estudiantes
GET http://localhost:5000/api/estudiantes



### Obtener información de estudiante
GET http://localhost:5000/api/estudiantes/{{cedula}}


### Agregar nuevo estudiante
POST http://localhost:5000/api/estudiantes
Content-Type: application/json

{
  "cedula":2354659,
  "nombre":"Julian",
  "apellido":"Parras",
  "correo":"julian.parra@misena.edu.co",
  "carrera":"Industrial"
}

### Actualizar estudiante
PUT http://localhost:5000/api/estudiantes/{{cedula2}}
Content-Type: application/json

{
    "cedula":2354656,
    "nombre":"Julian",
    "apellido":"Parras",
    "correo":"julian.parras@misena.edu.co",
    "carrera":"Electrónica"
}


### Eliminar Estudiante
DELETE http://localhost:5000/api/estudiantes/{{cedula2}}

### Agregar Petición
POST http://localhost:5000/api/estudiantes/{{cedula2}}/peticiones
Content-Type: application/json

{
  "cedula":2354659,
  "peticion":"Asesoría",
  "fecha_atencion":"25/09/20 7:00:00"
}


### Obtener Peticiones
GET http://localhost:5000/api/estudiantes/{{cedula2}}/peticiones
Content-Type: application/json


### Obtener Petición
GET http://localhost:5000/api/estudiantes/{{cedula2}}/peticiones/FXyLyC5t1ddLkmPbdaXA
Content-Type: application/json

### Actualizar Petición
PUT http://localhost:5000/api/estudiantes/{{cedula2}}/peticiones/FXyLyC5t1ddLkmPbdaXA
Content-Type: application/json

{
  "cedula":2354659,
  "peticion":"Asesoría",
  "fecha_atencion":"25/09/20 15:00:00"
}

### Borrar Petición
DELETE http://localhost:5000/api/estudiantes/{{cedula2}}/peticiones/FXyLyC5t1ddLkmPbdaXA
Content-Type: application/json