
### Hola Mundo
GET http://localhost:5000/

### Saludo
GET http://localhost:5000/saludo/jaime?titulo=Sr

### Listar todos los estudiantes
GET http://localhost:5000/estudiantes


@cedula=11234224
### Obtener información de estudiante
GET http://localhost:5000/estudiantes/{{cedula}}


